Improvements2 (#4)
This PR has following big changes
* COWBtree recovery test cases with variable cps and fixes

* Added cow btree crash test, updated other tests to ensure pass

* Btree Node allocators and variants

* Multiple Btreenode fixes

diff --git a/.github/workflows/build_dependencies.yml b/.github/workflows/build_dependencies.yml
--- a/.github/workflows/build_dependencies.yml
+++ b/.github/workflows/build_dependencies.yml
@@ -23,10 +23,10 @@ on:
         required: false
         type: string
         default: 'None'
-      testing:
+      build-level:
         required: false
         type: string
-        default: 'False'
+        default: 'Packaging'
   workflow_dispatch:
     inputs:
       platform:
@@ -71,17 +71,18 @@ on:
           - 'Coverage'
           - 'None'
         default: 'None'
-      testing:
-        description: 'Build and Run'
+      build-level:
+        description: 'Level to build'
         required: true
         type: choice
         options:
-          - 'True'
-          - 'False'
-        default: 'True'
+          - 'Dependencies'
+          - 'Packaging'
+          - 'Testing'
+        default: 'Testing'
 
 jobs:
-  BuildHomestoreDeps:
+  BuildHomestore:
     runs-on: ${{ inputs.platform }}
     timeout-minutes: 1440
     steps:
@@ -89,164 +90,288 @@ jobs:
       uses: actions/checkout@main
       with:
         ref: ${{ inputs.branch }}
-      if: ${{ inputs.testing == 'True' }}
+      if: ${{ inputs.build-level == 'Testing' }}
 
     - name: Retrieve Recipe
       uses: actions/checkout@main
       with:
         repository: hkadayam/Homestore
         ref: ${{ inputs.branch }}
-      if: ${{ inputs.testing == 'False' }}
+      if: ${{ inputs.build-level != 'Testing' }}
 
-    - name: Load Homestore Cache
+    - name: Restore Dependency Cache
       id: restore-cache
-      uses: hkadayam/sisl/.github/actions/load_conan@master
+      uses: actions/cache/restore@v4
       with:
-        testing: ${{ inputs.testing }}
-        key_prefix: HomestoreDeps-${{ inputs.platform }}-${{ inputs.build-type }}-${{ inputs.malloc-impl }}-${{ inputs.prerelease }}
+        path: |
+          ~/.conan2/p
+        key: HomestoreDeps-${{ inputs.platform }}-${{ inputs.build-type }}-${{ inputs.malloc-impl }}-${{ inputs.prerelease }}
+        fail-on-cache-miss: ${{ inputs.fail_on_cache_miss }}
 
-    - name: Load Sisl Cache
-      uses: hkadayam/sisl/.github/actions/load_conan@master
-      with:
-        load_any: 'True'
-        key_prefix: SislDeps-${{ inputs.platform }}-${{ inputs.build-type }}-${{ inputs.malloc-impl }}-${{ inputs.prerelease }}
-      if: ${{ inputs.testing == 'True' || steps.restore-cache.outputs.cache-hit != 'true' }}
-
-    - name: Retrieve Dependencies
+    - name: Retrieve IOManager code
       uses: actions/checkout@main
       with:
         repository: hkadayam/iomanager
         path: import/iomgr
         ref: master
-      if: ${{ inputs.testing == 'True' || steps.restore-cache.outputs.cache-hit != 'true' }}
 
-    - name: Retrieve Dependencies
+    - name: Retrieve NuraftMesg code
       uses: actions/checkout@main
       with:
         repository: hkadayam/nuraft_mesg
         path: import/nuraft_mesg
         ref: main
-      if: ${{ inputs.testing == 'True' || steps.restore-cache.outputs.cache-hit != 'true' }}
 
-    - name: Load IOMgr Cache
-      uses: hkadayam/sisl/.github/actions/load_conan@master
+    - name: Retrieve Sisl code
+      uses: actions/checkout@main
       with:
-        testing: 'False'
-        path: import/iomgr
-        key_prefix: IOMgrDeps-${{ inputs.platform }}-${{ inputs.build-type }}-${{ inputs.malloc-impl }}-${{ inputs.prerelease }}
-        fail_on_cache_miss: false
-      if: ${{ inputs.testing == 'True' || steps.restore-cache.outputs.cache-hit != 'true' }}
-
-    - name: Load NuraftMesg Cache
-      uses: hkadayam/sisl/.github/actions/load_conan@master
-      with:
-        testing: 'False'
-        path: import/nuraft_mesg
-        key_prefix: NuMesgDeps-${{ inputs.platform }}-${{ inputs.build-type }}-${{ inputs.malloc-impl }}-${{ inputs.prerelease }}
-        fail_on_cache_miss: false
-      if: ${{ inputs.testing == 'True' || steps.restore-cache.outputs.cache-hit != 'true' }}
+        repository: hkadayam/sisl
+        path: import/sisl
+        ref: master
 
     - name: Setup Conan
       uses: hkadayam/sisl/.github/actions/setup_conan@master
       with:
         platform: ${{ inputs.platform }}
-      if: ${{ inputs.testing == 'True' || steps.restore-cache.outputs.cache-hit != 'true' }}
 
-    - name: Export Recipes
+    - name: Export Recipes and DepsBuild Env
       run: |
-        sudo apt-get install -y python3-pyelftools libaio-dev
-        sudo rm -rf $ANDROID_HOME
-        python -m pip install pyelftools
-        conan export import/iomgr oss/master
-        conan export import/nuraft_mesg oss/main
-        cached_pkgs=$(ls -1d ~/.conan/data/*/*/*/*/package | sed 's,.*data/,,' | cut -d'/' -f1,2 | paste -sd',' - -)
-        echo "::info:: Pre-cached: ${cached_pkgs}"
-      if: ${{ inputs.testing == 'True' || steps.restore-cache.outputs.cache-hit != 'true' }}
+        conan export import/sisl --user oss --channel master
+        cd import/sisl && ./prepare.sh && cd ../..
+        conan export import/iomgr --user oss --channel master
+        cd import/iomgr && ./prepare.sh && cd ../..
+        conan export import/nuraft_mesg --user oss --channel main
+        cd import/nuraft_mesg/ && ./prepare.sh && cd ../..
 
-    - name: Build Cache
+    - name: Build Homestore Dependencies
+      id : build-deps
       run: |
-        pre=$([[ "${{ inputs.build-type }}" != "Debug" ]] && echo "-o sisl:prerelease=${{ inputs.prerelease }}" || echo "")
+        du -sh ~/.conan2/p | awk '{printf("size=%d\n", $1)}' > $GITHUB_OUTPUT
         conan install \
+            -u \
+            -o "sisl/*:prerelease=${{ inputs.prerelease }}" \
+            -o "sisl/*:malloc_impl=${{ inputs.malloc-impl }}" \
             -c tools.build:skip_test=True \
-            ${pre} \
-            -o sisl:malloc_impl=${{ inputs.malloc-impl }} \
-            -o iomgr:testing=off \
-            -o testing=off \
             -s build_type=${{ inputs.build-type }} \
             --build missing \
             .
-      if: ${{ steps.restore-cache.outputs.cache-hit != 'true' }}
 
-    - name: Save Conan Cache
-      uses: hkadayam/sisl/.github/actions/store_conan@master
+    - name: Remove Prior Dependencies
+      id : remove-prior-deps
+      run: |
+        conan remove -c -p "build_type=${{ inputs.build-type }}" '*:*#!latest'
+        du -sh ~/.conan2/p | awk '{printf("size=%d\n", $1)}' > $GITHUB_OUTPUT
+        rm -rf ~/.conan2/p/*/b ~/.conan2/p/*/s
+
+    - name: Save Cache
+      uses: actions/cache/save@v4
       with:
-        key_prefix: HomestoreDeps-${{ inputs.platform }}-${{ inputs.build-type }}-${{ inputs.malloc-impl }}-${{ inputs.prerelease }}
-      if: ${{ github.event_name != 'pull_request' && steps.restore-cache.outputs.cache-hit != 'true' }}
+        path: |
+          ~/.conan2/p
+        key: HomestoreDeps-${{ inputs.platform }}-${{ inputs.build-type }}-${{ inputs.malloc-impl }}-${{ inputs.prerelease }}
+      if: ${{ steps.build-deps.outputs.size != steps.remove-prior-deps.outputs.size }}
 
-    - name: Reload Sisl Cache
-      uses: hkadayam/sisl/.github/actions/load_conan@master
-      with:
-        load_any: 'True'
-        key_prefix: SislDeps-${{ inputs.platform }}-${{ inputs.build-type }}-${{ inputs.malloc-impl }}-${{ inputs.prerelease }}
-      if: ${{ inputs.testing == 'True' && github.event_name != 'pull_request' && steps.restore-cache.outputs.cache-hit != 'true' }}
-
-    - name: Reload IOMgr Cache
-      uses: hkadayam/sisl/.github/actions/load_conan@master
-      with:
-        testing: 'False'
-        path: import/iomgr
-        key_prefix: IOMgrDeps-${{ inputs.platform }}-${{ inputs.build-type }}-${{ inputs.malloc-impl }}-${{ inputs.prerelease }}
-        fail_on_cache_miss: true
-      if: ${{ inputs.testing == 'True' && github.event_name != 'pull_request' && steps.restore-cache.outputs.cache-hit != 'true' }}
-
-    - name: Reload NuraftMesg Cache
-      uses: hkadayam/sisl/.github/actions/load_conan@master
-      with:
-        testing: 'False'
-        path: import/nuraft_mesg
-        key_prefix: NuMesgDeps-${{ inputs.platform }}-${{ inputs.build-type }}-${{ inputs.malloc-impl }}-${{ inputs.prerelease }}
-        fail_on_cache_miss: true
-      if: ${{ inputs.testing == 'True' && github.event_name != 'pull_request' && steps.restore-cache.outputs.cache-hit != 'true' }}
-
-    - uses: actions/checkout@main
     - name: Setup tmate session
       uses: mxschmitt/action-tmate@v3
       with:
         limit-access-to-actor: true
         detached: true
-      if: ${{ inputs.testing == 'True' }}
 
     - name: Create and Test Package
       run: |
         sanitize=$([[ "${{ inputs.tooling }}" == "Sanitize" ]] && echo "True" || echo "False")
-        pre=$([[ "${{ inputs.build-type }}" != "Debug" ]] && echo "-o sisl:prerelease=${{ inputs.prerelease }}" || echo "")
+        skip_test=$([[ "${{ inputs.build-level }}" == "Testing" ]] && echo "False" || echo "True") 
         conan create \
-            ${pre} \
-            -o sisl:malloc_impl=${{ inputs.malloc-impl }} \
-            -o iomgr:testing=off \
-            -o homestore:sanitize=${sanitize} \
+            -o "sisl/*:prerelease=${{ inputs.prerelease }}" \
+            -o "sisl/*:malloc_impl=${{ inputs.malloc-impl }}" \
+            -o "homestore/*:sanitize=${sanitize}" \
+            -c tools.build:skip_test=${skip_test} \
             -s build_type=${{ inputs.build-type }} \
             --build missing \
             .
-      if: ${{ inputs.testing == 'True' && inputs.tooling != 'Coverage' }}
 
     - name: Code Coverage Run
       run: |
-        pre=$([[ "${{ inputs.build-type }}" != "Debug" ]] && echo "-o sisl:prerelease=${{ inputs.prerelease }}" || echo "")
-        conan install \
-            ${pre} \
-            -o sisl:malloc_impl=${{ inputs.malloc-impl }} \
-            -o iomgr:testing=off \
-            -o coverage=True \
+        conan build \
+            -o "sisl/*:prerelease=${{ inputs.prerelease }}" \
+            -o "sisl/*:malloc_impl=${{ inputs.malloc-impl }}" \
+            -c tools.build:skip_test=True \
             -s build_type=${{ inputs.build-type }} \
             --build missing \
             .
-        conan build .
-      if: ${{ inputs.testing == 'True' && inputs.tooling == 'Coverage' }}
+      if: ${{ inputs.tooling == 'Coverage' }}
 
     - name: Upload coverage reports to Codecov
       uses: codecov/codecov-action@v4
       with:
         token: ${{ secrets.CODECOV_TOKEN }}
         gcov: true
-      if: ${{ inputs.testing == 'True' && inputs.tooling == 'Coverage' }}
+      if: ${{ inputs.tooling == 'Coverage' }}
+
+
+# jobs:
+#   BuildHomestore:
+#     runs-on: ${{ inputs.platform }}
+#     timeout-minutes: 1440
+#     steps:
+#     - name: Retrieve Code
+#       uses: actions/checkout@main
+#       with:
+#         ref: ${{ inputs.branch }}
+#       if: ${{ inputs.build-level == 'Testing' }}
+
+#     - name: Retrieve Recipe
+#       uses: actions/checkout@main
+#       with:
+#         repository: hkadayam/Homestore
+#         ref: ${{ inputs.branch }}
+#       if: ${{ inputs.build-level != 'Testing' }}
+
+#     - name: Load HomestoreDeps Cache
+#       id: restore-cache
+#       uses: hkadayam/sisl/.github/actions/load_conan@master
+#       with:
+#         key_prefix: HomestoreDeps-${{ inputs.platform }}-${{ inputs.build-type }}-${{ inputs.malloc-impl }}-${{ inputs.prerelease }}
+
+#     - name: Load SislDeps Cache
+#       uses: hkadayam/sisl/.github/actions/load_conan@master
+#       with:
+#         load_any: 'True'
+#         key_prefix: SislDeps-${{ inputs.platform }}-${{ inputs.build-type }}-${{ inputs.malloc-impl }}-${{ inputs.prerelease }}
+#         fail_on_cache_miss: false
+#       if: ${{ steps.restore-cache.outputs.cache-hit != 'true' }}
+
+#     - name: Retrieve Dependencies
+#       uses: actions/checkout@main
+#       with:
+#         repository: hkadayam/iomanager
+#         path: import/iomgr
+#         ref: master
+#       if: ${{ steps.restore-cache.outputs.cache-hit != 'true' || inputs.build-level != 'Dependencies' }}
+
+#     - name: Retrieve Dependencies
+#       uses: actions/checkout@main
+#       with:
+#         repository: hkadayam/nuraft_mesg
+#         path: import/nuraft_mesg
+#         ref: main
+#       if: ${{ steps.restore-cache.outputs.cache-hit != 'true' || inputs.build-level != 'Dependencies' }}
+
+#     - name: Load IOMgr Cache
+#       uses: hkadayam/sisl/.github/actions/load_conan@master
+#       with:
+#         path: import/iomgr
+#         key_prefix: IOMgrDeps-${{ inputs.platform }}-${{ inputs.build-type }}-${{ inputs.malloc-impl }}-${{ inputs.prerelease }}
+#         fail_on_cache_miss: false
+#       if: ${{ steps.restore-cache.outputs.cache-hit != 'true' }}
+
+#     - name: Load NuraftMesgDeps Cache
+#       uses: hkadayam/sisl/.github/actions/load_conan@master
+#       with:
+#         path: import/nuraft_mesg
+#         key_prefix: NuMesgDeps-${{ inputs.platform }}-${{ inputs.build-type }}-${{ inputs.malloc-impl }}-${{ inputs.prerelease }}
+#         fail_on_cache_miss: false
+#       if: ${{ steps.restore-cache.outputs.cache-hit != 'true' }}
+
+#     - name: Setup Conan
+#       uses: hkadayam/sisl/.github/actions/setup_conan@master
+#       with:
+#         platform: ${{ inputs.platform }}
+#       if: ${{ steps.restore-cache.outputs.cache-hit != 'true' || inputs.build-level != 'Dependencies' }}
+
+#     - name: Export Recipes
+#       run: |
+#         sudo apt-get install -y python3-pyelftools libaio-dev
+#         sudo rm -rf $ANDROID_HOME
+#         python -m pip install pyelftools
+#         conan export import/iomgr oss/master
+#         conan export import/nuraft_mesg oss/main
+#         cached_pkgs=$(ls -1d ~/.conan/data/*/*/*/*/package | sed 's,.*data/,,' | cut -d'/' -f1,2 | paste -sd',' - -)
+#         echo "::info:: Pre-cached: ${cached_pkgs}"
+#       if: ${{ steps.restore-cache.outputs.cache-hit != 'true' || inputs.build-level != 'Dependencies' }}
+
+#     - name: Build Homestore Deps Cache
+#       run: |
+#         pre=$([[ "${{ inputs.build-type }}" != "Debug" ]] && echo "-o sisl/*:prerelease=${{ inputs.prerelease }}" || echo "")
+#         conan install \
+#             -c tools.build:skip_test=True \
+#             ${pre} \
+#             -o sisl:malloc_impl=${{ inputs.malloc-impl }} \
+#             -o iomgr:testing=off \
+#             -o testing=off \
+#             -s build_type=${{ inputs.build-type }} \
+#             --build missing \
+#             .
+#       if: ${{ steps.restore-cache.outputs.cache-hit != 'true' }}
+
+#     - name: Save Homestore Deps Cache
+#       uses: hkadayam/sisl/.github/actions/store_conan@master
+#       with:
+#         key_prefix: HomestoreDeps-${{ inputs.platform }}-${{ inputs.build-type }}-${{ inputs.malloc-impl }}-${{ inputs.prerelease }}
+#       if: ${{ steps.restore-cache.outputs.cache-hit != 'true' }}
+
+#     - name: Reload Sisl Cache
+#       uses: hkadayam/sisl/.github/actions/load_conan@master
+#       with:
+#         load_any: 'True'
+#         key_prefix: SislDeps-${{ inputs.platform }}-${{ inputs.build-type }}-${{ inputs.malloc-impl }}-${{ inputs.prerelease }}
+#       if: ${{ inputs.build-level != 'Dependencies' && steps.restore-cache.outputs.cache-hit != 'true' }}
+
+#     - name: Reload IOMgr Cache
+#       uses: hkadayam/sisl/.github/actions/load_conan@master
+#       with:
+#         path: import/iomgr
+#         key_prefix: IOMgrDeps-${{ inputs.platform }}-${{ inputs.build-type }}-${{ inputs.malloc-impl }}-${{ inputs.prerelease }}
+#         fail_on_cache_miss: true
+#       if: ${{ inputs.build-level != 'Dependencies' && steps.restore-cache.outputs.cache-hit != 'true' }}
+
+#     - name: Reload NuraftMesg Cache
+#       uses: hkadayam/sisl/.github/actions/load_conan@master
+#       with:
+#         path: import/nuraft_mesg
+#         key_prefix: NuMesgDeps-${{ inputs.platform }}-${{ inputs.build-type }}-${{ inputs.malloc-impl }}-${{ inputs.prerelease }}
+#         fail_on_cache_miss: true
+#       if: ${{ inputs.build-level != 'Dependencies' && steps.restore-cache.outputs.cache-hit != 'true' }}
+
+#     - uses: actions/checkout@main
+#     - name: Setup tmate session
+#       uses: mxschmitt/action-tmate@v3
+#       with:
+#         limit-access-to-actor: true
+#         detached: true
+#       if: ${{ inputs.build-level != 'Dependencies' }}
+
+#     - name: Create and Test Package
+#       run: |
+#         sanitize=$([[ "${{ inputs.tooling }}" == "Sanitize" ]] && echo "True" || echo "False")
+#         pre=$([[ "${{ inputs.build-type }}" != "Debug" ]] && echo "-o sisl:prerelease=${{ inputs.prerelease }}" || echo "")
+#         conan create \
+#             ${pre} \
+#             -o "sisl/*:malloc_impl=${{ inputs.malloc-impl }}"" \
+#             -o "iomgr/*:testing=off" \
+#             -o "homestore/*:sanitize=${sanitize}"" \
+#             -s build_type=${{ inputs.build-type }} \
+#             --build missing \
+#             .
+#       if: ${{ inputs.build-level != 'Dependencies' && inputs.tooling != 'Coverage' }}
+
+#     - name: Code Coverage Run
+#       run: |
+#         pre=$([[ "${{ inputs.build-type }}" != "Debug" ]] && echo "-o sisl:prerelease=${{ inputs.prerelease }}" || echo "")
+#         conan install \
+#             ${pre} \
+#             -o "sisl/*:malloc_impl=${{ inputs.malloc-impl }}"" \
+#             -o "iomgr/*:testing=off" \
+#             -o coverage=True \
+#             -s build_type=${{ inputs.build-type }} \
+#             --build missing \
+#             .
+#         conan build .
+#       if: ${{ inputs.build-level != 'Dependencies' && inputs.tooling == 'Coverage' }}
+
+#     - name: Upload coverage reports to Codecov
+#       uses: codecov/codecov-action@v4
+#       with:
+#         token: ${{ secrets.CODECOV_TOKEN }}
+#         gcov: true
+#       if: ${{ inputs.build-level != 'Dependencies' && inputs.tooling == 'Coverage' }}
